import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    appName: "Rythu Sethu",
    tagline: "Bridging Farmers & Customers",
    login: "Login",
    register: "Register",
    logout: "Logout",
    email: "Email Address",
    password: "Password",
    name: "Full Name",
    phone: "Phone Number",
    role: "I am a",
    farmer: "Farmer",
    customer: "Customer",
    agent: "Delivery Agent",
    marketplace: "Marketplace",
    dashboard: "Dashboard",
    addCrop: "Add Crop",
    cropName: "Crop Name",
    price: "Price (₹)",
    quantity: "Quantity",
    location: "Location",
    autoLocation: "Auto-detect Location",
    submit: "Submit",
    loading: "Loading...",
    success: "Success!",
    error: "Error",
    orders: "Orders",
    deliveries: "Deliveries",
    adminPanel: "Admin Panel",
    welcome: "Welcome",
    noData: "No data found",
    search: "Search...",
    cropSuggest: "Crop Suggestions",
    nutritionInfo: "Nutrition Info",
    demandForecast: "Demand Forecast",
    farmerTips: "Farming Tips",
    farmName: "Farm Name",
    farmSize: "Farm Size (acres)",
    soilType: "Soil Type",
    experience: "Experience (years)",
    address: "Delivery Address",
    buy: "Buy Now",
    outOfStock: "Out of Stock",
    status: "Status",
    temperature: "Temperature (°C)",
    humidity: "Humidity (%)",
    rainfall: "Rainfall (mm)",
    analyze: "Analyze",
    languagePref: "Preferred Language",
    aadhaar: "Aadhaar Number (optional)",
    organic: "Organic Product",
    category: "Category",
    description: "Description",
    season: "Season",
  },
  te: {
    appName: "రైతు సేతు",
    tagline: "రైతులు & వినియోగదారులను కలుపుతోంది",
    login: "లాగిన్",
    register: "నమోదు",
    logout: "లాగ్అవుట్",
    email: "ఇమెయిల్ చిరునామా",
    password: "పాస్వర్డ్",
    name: "పూర్తి పేరు",
    phone: "ఫోన్ నంబర్",
    role: "నేను ఒక",
    farmer: "రైతు",
    customer: "వినియోగదారుడు",
    agent: "డెలివరీ ఏజెంట్",
    marketplace: "మార్కెట్‌ప్లేస్",
    dashboard: "డాష్‌బోర్డ్",
    addCrop: "పంటను జోడించు",
    cropName: "పంట పేరు",
    price: "ధర (₹)",
    quantity: "పరిమాణం",
    location: "స్థానం",
    autoLocation: "స్వీయ స్థానం",
    submit: "సమర్పించు",
    loading: "లోడవుతోంది...",
    success: "విజయం!",
    error: "లోపం",
    orders: "ఆర్డర్లు",
    deliveries: "డెలివరీలు",
    adminPanel: "అడ్మిన్ ప్యానెల్",
    welcome: "స్వాగతం",
    noData: "డేటా లేదు",
    search: "వెతకండి...",
    cropSuggest: "పంట సూచనలు",
    nutritionInfo: "పోషకాహార సమాచారం",
    demandForecast: "డిమాండ్ అంచనా",
    farmerTips: "వ్యవసాయ చిట్కాలు",
    farmName: "పొలం పేరు",
    farmSize: "పొలం పరిమాణం (ఎకరాలు)",
    soilType: "నేల రకం",
    experience: "అనుభవం (సంవత్సరాలు)",
    address: "డెలివరీ చిరునామా",
    buy: "కొనుగోలు చేయి",
    outOfStock: "స్టాక్ లేదు",
    status: "స్థితి",
    temperature: "ఉష్ణోగ్రత (°C)",
    humidity: "తేమ (%)",
    rainfall: "వర్షపాతం (mm)",
    analyze: "విశ్లేషించు",
    languagePref: "భాష ప్రాధాన్యత",
    aadhaar: "ఆధార్ నంబర్ (ఐచ్ఛికం)",
    organic: "సేంద్రీయ ఉత్పత్తి",
    category: "వర్గం",
    description: "వివరణ",
    season: "సీజన్",
  },
  hi: {
    appName: "रैतु सेतु",
    tagline: "किसानों और ग्राहकों को जोड़ना",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआउट",
    email: "ईमेल पता",
    password: "पासवर्ड",
    name: "पूरा नाम",
    phone: "फोन नंबर",
    role: "मैं हूं",
    farmer: "किसान",
    customer: "ग्राहक",
    agent: "डिलीवरी एजेंट",
    marketplace: "बाज़ार",
    dashboard: "डैशबोर्ड",
    addCrop: "फसल जोड़ें",
    cropName: "फसल का नाम",
    price: "कीमत (₹)",
    quantity: "मात्रा",
    location: "स्थान",
    autoLocation: "स्वतः स्थान",
    submit: "जमा करें",
    loading: "लोड हो रहा है...",
    success: "सफलता!",
    error: "त्रुटि",
    orders: "ऑर्डर",
    deliveries: "डिलीवरी",
    adminPanel: "एडमिन पैनल",
    welcome: "स्वागत है",
    noData: "डेटा नहीं मिला",
    search: "खोजें...",
    cropSuggest: "फसल सुझाव",
    nutritionInfo: "पोषण जानकारी",
    demandForecast: "मांग पूर्वानुमान",
    farmerTips: "खेती के सुझाव",
    farmName: "खेत का नाम",
    farmSize: "खेत का आकार (एकड़)",
    soilType: "मिट्टी का प्रकार",
    experience: "अनुभव (वर्ष)",
    address: "डिलीवरी पता",
    buy: "अभी खरीदें",
    outOfStock: "स्टॉक में नहीं",
    status: "स्थिति",
    temperature: "तापमान (°C)",
    humidity: "आर्द्रता (%)",
    rainfall: "वर्षा (mm)",
    analyze: "विश्लेषण करें",
    languagePref: "भाषा प्राथमिकता",
    aadhaar: "आधार नंबर (वैकल्पिक)",
    organic: "जैविक उत्पाद",
    category: "श्रेणी",
    description: "विवरण",
    season: "मौसम",
  }
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");

  const changeLang = (l) => {
    setLang(l);
    localStorage.setItem("lang", l);
  };

  const t = (key) => translations[lang]?.[key] || translations["en"][key] || key;

  return (
    <LangContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
