import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    appName: "Rythu Sethu",
    tagline: "Bridging Farmers & Customers",
    login: "Login",
    register: "Register",
    logout: "Logout",
    email: "Email Address",
    password: "Password",
    name: "Full Name",
    phone: "Phone Number",
    role: "I am a",
    farmer: "Farmer",
    customer: "Customer",
    agent: "Delivery Agent",
    marketplace: "Marketplace",
    dashboard: "Dashboard",
    addCrop: "Add Crop",
    cropName: "Crop Name",
    price: "Price (₹)",
    quantity: "Quantity",
    location: "Location",
    autoLocation: "Auto-detect Location",
    submit: "Submit",
    loading: "Loading...",
    success: "Success!",
    error: "Error",
    orders: "Orders",
    deliveries: "Deliveries",
    adminPanel: "Admin Panel",
    welcome: "Welcome",
    noData: "No data found",
    search: "Search...",
    cropSuggest: "Crop Suggestions",
    nutritionInfo: "Nutrition Info",
    demandForecast: "Demand Forecast",
    farmerTips: "Farming Tips",
    farmName: "Farm Name",
    farmSize: "Farm Size (acres)",
    soilType: "Soil Type",
    experience: "Experience (years)",
    address: "Delivery Address",
    buy: "Buy Now",
    outOfStock: "Out of Stock",
    status: "Status",
    temperature: "Temperature (°C)",
    humidity: "Humidity (%)",
    rainfall: "Rainfall (mm)",
    analyze: "Analyze",
    languagePref: "Preferred Language",
    aadhaar: "Aadhaar Number (optional)",
    organic: "Organic Product",
    category: "Category",
    description: "Description",
    season: "Season",
    allItems: "All Items",
    veggies: "Veggies",
    fruits: "Fruits",
    grains: "Grains",
    adminVerify: "Admin Verify",
    agentHub: "Agent Hub",
    outForDelivery: "Out for Delivery",
    getStarted: "Get Started Free",
    shopNow: "Shop Now",
    isPrebooking: "Available for Pre-booking",
    harvestDate: "Expected Harvest Date",
    preBook: "Pre-book",
    preBooked: "Pre-booked",
    rewardPoints: "Reward Points",
    experiencePoints: "Experience Points",
    usePoints: "Use Points for Discount",

    home: 'Home',
    seasonalSpecials: 'Seasonal Specials',
    freshlyHarvested: 'Freshly harvested this season!',
    list: 'List',
    map: 'Map',
    placeOrder: 'Place Order',
    deliveryOption: 'Delivery Option',
    buyAtFarm: 'Buy at Farm',
    homeDelivery: 'Home Delivery',
    paymentMethod: 'Payment Method',
    cashOnDelivery: 'Cash on Delivery',
    payOnline: 'Pay Online',
    apply: 'Apply',
    billPreview: 'Bill Preview',
    total: 'Total',
    fetchWeather: 'Fetch Live Weather',
    detecting: 'Detecting...',
    weatherData: 'Weather Data',
    demandForecaster: 'Demand Forecaster',
    predictDemand: 'Predict Demand',
    analyzing: 'Analyzing...',
    smartRoute: 'Smart Route Optimize',
    optimizing: 'Optimizing...',
    routeGenerated: 'Smart Route Generated',
    totalDistance: 'Total Distance',
    notifications: 'Notifications',
    unread: 'Unread',
    noNotifications: 'No new notifications',
    myOrders: 'My Orders',
    cancel: 'Cancel',
    confirm: 'Confirm',
    printBill: 'Print Bill',
  },
  te: {
    appName: "రైతు సేతు",
    tagline: "రైతులు & వినియోగదారులను కలుపుతోంది",
    login: "లాగిన్",
    register: "నమోదు",
    logout: "లాగ్అవుట్",
    email: "ఇమెయిల్ చిరునామా",
    password: "పాస్వర్డ్",
    name: "పూర్తి పేరు",
    phone: "ఫోన్ నంబర్",
    role: "నేను ఒక",
    farmer: "రైతు",
    customer: "వినియోగదారుడు",
    agent: "డెలివరీ ఏజెంట్",
    marketplace: "మార్కెట్‌ప్లేస్",
    dashboard: "డాష్‌బోర్డ్",
    addCrop: "పంటను జోడించు",
    cropName: "పంట పేరు",
    price: "ధర (₹)",
    quantity: "పరిమాణం",
    location: "స్థానం",
    autoLocation: "స్వీయ స్థానం",
    submit: "సమర్పించు",
    loading: "లోడవుతోంది...",
    success: "విజయం!",
    error: "లోపం",
    orders: "ఆర్డర్లు",
    deliveries: "డెలివరీలు",
    adminPanel: "అడ్మిన్ ప్యానెల్",
    welcome: "స్వాగతం",
    noData: "డేటా లేదు",
    search: "వెతకండి...",
    cropSuggest: "పంట సూచనలు",
    nutritionInfo: "పోషకాహార సమాచారం",
    demandForecast: "డిమాండ్ అంచనా",
    farmerTips: "వ్యవసాయ చిట్కాలు",
    farmName: "పొలం పేరు",
    farmSize: "పొలం పరిమాణం (ఎకరాలు)",
    soilType: "నేల రకం",
    experience: "అనుభవం (సంవత్సరాలు)",
    address: "డెలివరీ చిరునామా",
    buy: "కొనుగోలు చేయి",
    outOfStock: "స్టాక్ లేదు",
    status: "స్థితి",
    temperature: "ఉష్ణోగ్రత (°C)",
    humidity: "తేమ (%)",
    rainfall: "వర్షపాతం (mm)",
    analyze: "విశ్లేషించు",
    languagePref: "భాష ప్రాధాన్యత",
    aadhaar: "ఆధార్ నంబర్ (ఐచ్ఛికం)",
    organic: "సేంద్రీయ ఉత్పత్తి",
    category: "వర్గం",
    description: "వివరణ",
    season: "సీజన్",
    allItems: "అన్ని వస్తువులు",
    veggies: "కూరగాయలు",
    fruits: "పండ్లు",
    grains: "ధాన్యాలు",
    adminVerify: "అడ్మిన్ ధృవీకరణ",
    agentHub: "ఏజెంట్ హబ్",
    outForDelivery: "డెలివరీ కోసం",
    getStarted: "ఉచితంగా ప్రారంభించండి",
    shopNow: "ఇప్పుడే కొనండి",
    isPrebooking: "ప్రీ-బుకింగ్ కోసం అందుబాటులో ఉంది",
    harvestDate: "ఆశించిన కోత తేదీ",
    preBook: "ముందుగా బుక్ చేయండి",
    preBooked: "ముందుగా బుక్ చేయబడింది",
    rewardPoints: "రివార్డ్ పాయింట్లు",
    experiencePoints: "అనుభవ పాయింట్లు",
    usePoints: "డిస్కౌంట్ కోసం పాయింట్లను ఉపయోగించండి",

    home: 'హోమ్',
    seasonalSpecials: 'సీజనల్ స్పెషల్స్',
    freshlyHarvested: 'ఈ సీజన్‌లో తాజాగా పండించినవి!',
    list: 'జాబితా',
    map: 'మ్యాప్',
    placeOrder: 'ఆర్డర్ చేయండి',
    deliveryOption: 'డెలివరీ ఎంపిక',
    buyAtFarm: 'పొలంలో కొనండి',
    homeDelivery: 'హోమ్ డెలివరీ',
    paymentMethod: 'చెల్లింపు పద్ధతి',
    cashOnDelivery: 'క్యాష్ ఆన్ డెలివరీ',
    payOnline: 'ఆన్‌లైన్ చెల్లింపు',
    apply: 'వర్తించు',
    billPreview: 'బిల్లు ప్రివ్యూ',
    total: 'మొత్తం',
    fetchWeather: 'వాతావరణం పొందండి',
    detecting: 'గుర్తిస్తోంది...',
    weatherData: 'వాతావరణ డేటా',
    demandForecaster: 'డిమాండ్ అంచనా',
    predictDemand: 'డిమాండ్ అంచనా వేయండి',
    analyzing: 'విశ్లేషిస్తోంది...',
    smartRoute: 'స్మార్ట్ రూట్ ఆప్టిమైజ్',
    optimizing: 'ఆప్టిమైజ్ చేస్తోంది...',
    routeGenerated: 'స్మార్ట్ రూట్ రూపొందించబడింది',
    totalDistance: 'మొత్తం దూరం',
    notifications: 'నోటిఫికేషన్‌లు',
    unread: 'చదవనివి',
    noNotifications: 'కొత్త నోటిఫికేషన్‌లు లేవు',
    myOrders: 'నా ఆర్డర్‌లు',
    cancel: 'రద్దు చేయి',
    confirm: 'నిర్ధారించు',
    printBill: 'బిల్లు ప్రింట్ చేయండి',
  },
  hi: {
    appName: "रैतु सेतु",
    tagline: "किसानों और ग्राहकों को जोड़ना",
    login: "लॉगिन",
    register: "पंजीकरण",
    logout: "लॉगआउट",
    email: "ईमेल पता",
    password: "पासवर्ड",
    name: "पूरा नाम",
    phone: "फोन नंबर",
    role: "मैं हूं",
    farmer: "किसान",
    customer: "ग्राहक",
    agent: "डिलीवरी एजेंट",
    marketplace: "बाज़ार",
    dashboard: "डैशबोर्ड",
    addCrop: "फसल जोड़ें",
    cropName: "फसल का नाम",
    price: "कीमत (₹)",
    quantity: "मात्रा",
    location: "स्थान",
    autoLocation: "स्वतः स्थान",
    submit: "जमा करें",
    loading: "लोड हो रहा है...",
    success: "सफलता!",
    error: "त्रुटि",
    orders: "ऑर्डर",
    deliveries: "डिलीवरी",
    adminPanel: "एडमिन पैनल",
    welcome: "स्वागत है",
    noData: "डेटा नहीं मिला",
    search: "खोजें...",
    cropSuggest: "फसल सुझाव",
    nutritionInfo: "पोषण जानकारी",
    demandForecast: "मांग पूर्वानुमान",
    farmerTips: "खेती के सुझाव",
    farmName: "खेत का नाम",
    farmSize: "खेत का आकार (एकड़)",
    soilType: "मिट्टी का प्रकार",
    experience: "अनुभव (वर्ष)",
    address: "डिलीवरी पता",
    buy: "अभी खरीदें",
    outOfStock: "स्टॉक में नहीं",
    status: "स्थिति",
    temperature: "तापमान (°C)",
    humidity: "आर्द्रता (%)",
    rainfall: "वर्षा (mm)",
    analyze: "विश्लेषण करें",
    languagePref: "भाषा प्राथमिकता",
    aadhaar: "आधार नंबर (वैकल्पिक)",
    organic: "जैविक उत्पाद",
    category: "श्रेणी",
    description: "विवरण",
    season: "मौसम",
    allItems: "सभी वस्तुएं",
    veggies: "सब्जियां",
    fruits: "फल",
    grains: "अनाज",
    adminVerify: "व्यवस्थापक सत्यापन",
    agentHub: "एजेंट हब",
    outForDelivery: "डिलीवरी के लिए तैयार",
    getStarted: "मुफ्त में शुरू करें",
    shopNow: "अभी खरीदें",
    isPrebooking: "प्री-बुकिंग के लिए उपलब्ध",
    harvestDate: "फसल कटाई की संभावित तिथि",
    preBook: "प्री-बुक",
    preBooked: "प्री-बुक किया गया",
    rewardPoints: "इनाम अंक",
    experiencePoints: "अनुभव अंक",
    usePoints: "छूट के लिए अंकों का उपयोग करें",

    home: 'होम',
    seasonalSpecials: 'मौसमी विशेष',
    freshlyHarvested: 'इस मौसम में ताज़ा काटा गया!',
    list: 'सूची',
    map: 'नक्शा',
    placeOrder: 'ऑर्डर करें',
    deliveryOption: 'डिलीवरी विकल्प',
    buyAtFarm: 'खेत पर खरीदें',
    homeDelivery: 'होम डिलीवरी',
    paymentMethod: 'भुगतान विधि',
    cashOnDelivery: 'कैश ऑन डिलीवरी',
    payOnline: 'ऑनलाइन भुगतान करें',
    apply: 'लागू करें',
    billPreview: 'बिल पूर्वावलोकन',
    total: 'कुल',
    fetchWeather: 'मौसम की जानकारी लाएं',
    detecting: 'पता लगा रहा है...',
    weatherData: 'मौसम डेटा',
    demandForecaster: 'मांग पूर्वानुमानकर्ता',
    predictDemand: 'मांग का अनुमान लगाएं',
    analyzing: 'विश्लेषण कर रहा है...',
    smartRoute: 'स्मार्ट मार्ग अनुकूलित करें',
    optimizing: 'अनुकूलित कर रहा है...',
    routeGenerated: 'स्मार्ट मार्ग उत्पन्न',
    totalDistance: 'कुल दूरी',
    notifications: 'सूचनाएं',
    unread: 'अपठित',
    noNotifications: 'कोई नई सूचना नहीं',
    myOrders: 'मेरे ऑर्डर',
    cancel: 'रद्द करें',
    confirm: 'पुष्टि करें',
    printBill: 'बिल प्रिंट करें',
  },
  kn: {
    appName: "ರೈತು ಸೇತು",
    tagline: "ರೈತರು ಮತ್ತು ಗ್ರಾಹಕರನ್ನು ಜೋಡಿಸುವುದು",
    login: "ಲಾಗಿನ್",
    register: "ನೋಂದಣಿ",
    logout: "ಲಾಗ್ ಔಟ್",
    email: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಪಾಸ್ವರ್ಡ್",
    name: "ಪೂರ್ಣ ಹೆಸರು",
    phone: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    role: "ನಾನು",
    farmer: "ರೈತ",
    customer: "ಗ್ರಾಹಕ",
    agent: "ಡೆಲಿವರಿ ಏಜೆಂಟ್",
    marketplace: "ಮಾರುಕಟ್ಟೆ",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    addCrop: "ಬೆಳೆ ಸೇರಿಸಿ",
    cropName: "ಬೆಳೆ ಹೆಸರು",
    price: "ಬೆಲೆ (₹)",
    quantity: "ಪ್ರಮಾಣ",
    location: "ಸ್ಥಳ",
    autoLocation: "ಸ್ವಯಂ ಸ್ಥಳ ಪತ್ತೆ",
    submit: "ಸಲ್ಲಿಸು",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    success: "ಯಶಸ್ಸು!",
    error: "ದೋಷ",
    orders: "ಆರ್ಡರ್‌ಗಳು",
    deliveries: "ಡೆಲಿವರಿಗಳು",
    adminPanel: "ನಿರ್ವಾಹಕ ಫಲಕ",
    welcome: "ಸ್ವಾಗತ",
    noData: "ಮಾಹಿತಿ ಇಲ್ಲ",
    search: "ಹುಡುಕಿ...",
    cropSuggest: "ಬೆಳೆ ಸಲಹೆಗಳು",
    nutritionInfo: "ಪೌಷ್ಟಿಕಾಂಶ ಮಾಹಿತಿ",
    demandForecast: "ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ",
    farmerTips: "ವ್ಯವಸಾಯ ಸಲಹೆಗಳು",
    farmName: "ಹೊಲದ ಹೆಸರು",
    farmSize: "ಹೊಲದ ಗಾತ್ರ (ಎಕರೆ)",
    soilType: "ಮಣ್ಣಿನ ವಿಧ",
    experience: "ಅನ್ಯುಭವ (ವರ್ಷಗಳು)",
    address: "ವಿತರಣಾ ವಿಳಾಸ",
    buy: "ಖರೀದಿಸಿ",
    outOfStock: "ದಾಸ್ತಾನು ಇಲ್ಲ",
    status: "ಸ್ಥಿತಿ",
    temperature: "ತಾಪಮಾನ (°C)",
    humidity: "ಆರ್ದ್ರತೆ (%)",
    rainfall: "ಮಳೆ ಪ್ರಮಾಣ (mm)",
    analyze: "ವಿಶ್ಲೇಷಿಸು",
    languagePref: "ಆದ್ಯತೆಯ ಭಾಷೆ",
    aadhaar: "ಆಧಾರ್ ಸಂಖ್ಯೆ (ಐಚ್ಛಿಕ)",
    organic: "ಸಾವಯವ ಉತ್ಪನ್ನ",
    category: "ವರ್ಗ",
    description: "ವಿವರಣೆ",
    season: "ಋತು",
    allItems: "ಎಲ್ಲಾ ವಸ್ತುಗಳು",
    veggies: "ತರಕಾರಿಗಳು",
    fruits: "ಹಣ್ಣುಗಳು",
    grains: "ಧಾನ್ಯಗಳು",
    adminVerify: "ನಿರ್ವಾಹಕರ ಪರಿಶೀಲನೆ",
    agentHub: "ಏಜೆಂಟ್ ಹಬ್",
    outForDelivery: "ವಿತರಣೆಗೆ ಸಿದ್ಧ",
    getStarted: "ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ",
    shopNow: "ಈಗ ಖರೀದಿಸಿ",
    isPrebooking: "ಪ್ರೀ-ಬುಕಿಂಗ್‌ಗೆ ಲಭ್ಯವಿದೆ",
    harvestDate: "ನಿರೀಕ್ಷಿತ ಕಟಾವು ದಿನಾಂಕ",
    preBook: "ಪ್ರೀ-ಬುಕ್",
    preBooked: "ಪ್ರೀ-ಬುಕ್ ಮಾಡಲಾಗಿದೆ",
    rewardPoints: "ರಿವಾರ್ಡ್ ಪಾಯಿಂಟ್‌ಗಳು",
    experiencePoints: "ಅನುಭವ ಪಾಯಿಂಟ್‌ಗಳು",
    usePoints: "ರಿಯಾಯಿತಿಗಾಗಿ ಪಾಯಿಂಟ್‌ಗಳನ್ನು ಬಳಸಿ",

    home: 'ಮುಖಪುಟ',
    seasonalSpecials: 'ಋತುಮಾನದ ವಿಶೇಷತೆಗಳು',
    freshlyHarvested: 'ಈ ಋತುವಿನಲ್ಲಿ ತಾಜಾವಾಗಿ ಕಟಾವು ಮಾಡಲಾಗಿದೆ!',
    list: 'ಪಟ್ಟಿ',
    map: 'ನಕ್ಷೆ',
    placeOrder: 'ಆರ್ಡರ್ ಮಾಡಿ',
    deliveryOption: 'ವಿತರಣೆ ಆಯ್ಕೆ',
    buyAtFarm: 'ಹೊಲದಲ್ಲಿ ಖರೀದಿಸಿ',
    homeDelivery: 'ಮನೆ ವಿತರಣೆ',
    paymentMethod: 'ಪಾವತಿ ವಿಧಾನ',
    cashOnDelivery: 'ವಿತರಣೆಯ ನಂತರ ನಗದು',
    payOnline: 'ಆನ್‌ಲೈನ್ ಪಾವತಿಸಿ',
    apply: 'ಅನ್ವಯಿಸು',
    billPreview: 'ಬಿಲ್ ಮುನ್ನೋಟ',
    total: 'ಒಟ್ಟು',
    fetchWeather: 'ಹವಾಮಾನ ಮಾಹಿತಿ ಪಡೆಯಿರಿ',
    detecting: 'ಪತ್ತೆಹಚ್ಚಲಾಗುತ್ತಿದೆ...',
    weatherData: 'ಹವಾಮಾನ ಡೇಟಾ',
    demandForecaster: 'ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆಕಾರ',
    predictDemand: 'ಬೇಡಿಕೆಯನ್ನು ಅಂದಾಜು ಮಾಡಿ',
    analyzing: 'ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    smartRoute: 'ಸ್ಮಾರ್ಟ್ ಮಾರ್ಗ ಆಪ್ಟಿಮೈಸ್',
    optimizing: 'ಆಪ್ಟಿಮೈಸ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    routeGenerated: 'ಸ್ಮಾರ್ಟ್ ಮಾರ್ಗ ರಚಿಸಲಾಗಿದೆ',
    totalDistance: 'ಒಟ್ಟು ದೂರ',
    notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    unread: 'ಓದದಿರುವ',
    noNotifications: 'ಯಾವುದೇ ಹೊಸ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ',
    myOrders: 'ನನ್ನ ಆರ್ಡರ್‌ಗಳು',
    cancel: 'ರದ್ದುಮಾಡು',
    confirm: 'ಖಚಿತಪಡಿಸಿ',
    printBill: 'ಬಿಲ್ ಮುದ್ರಿಸಿ',
  },
  ta: {
    appName: "ரைத்து சேது",
    tagline: "விவசாயிகளையும் வாடிக்கையாளர்களையும் இணைக்கிறது",
    login: "உள்நுழை",
    register: "பதிவு செய்",
    logout: "வெளியேறு",
    email: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    name: "முழு பெயர்",
    phone: "தொலைபேசி எண்",
    role: "நான் ஒரு",
    farmer: "விவசாயி",
    customer: "வாடிக்கையாளர்",
    agent: "டெலிவரி முகவர்",
    marketplace: "சந்தை",
    dashboard: "டாஷ்போர்டு",
    addCrop: "பயிரைச் சேர்",
    cropName: "பயிர் பெயர்",
    price: "விலை (₹)",
    quantity: "அளவு",
    location: "இடம்",
    autoLocation: "தானியங்கி இருப்பிடம்",
    submit: "சமர்ப்பி",
    loading: "ஏற்றப்படுகிறது...",
    success: "வெற்றி!",
    error: "பிழை",
    orders: "ஆர்டர்கள்",
    deliveries: "டெலிவரிகள்",
    adminPanel: "நிர்வாக குழு",
    welcome: "வரவேற்பு",
    noData: "தரவு எதுவும் இல்லை",
    search: "தேடுக...",
    cropSuggest: "பயிர் ஆலோசனைகள்",
    nutritionInfo: "ஊட்டச்சத்து தகவல்",
    demandForecast: "தேவை கணிப்பு",
    farmerTips: "விவசாய குறிப்புகள்",
    farmName: "பண்ணை பெயர்",
    farmSize: "பண்ணை அளவு (ஏக்கர்)",
    soilType: "மண் வகை",
    experience: "அனுபவம் (ஆண்டுகள்)",
    address: "டெலிவரி முகவரி",
    buy: "இப்போதே வாங்கு",
    outOfStock: "இருப்பு இல்லை",
    status: "நிலை",
    temperature: "வெப்பநிலை (°C)",
    humidity: "ஈரப்பதம் (%)",
    rainfall: "மழைப்பொழிவு (mm)",
    analyze: "பகுப்பாய்வு செய்",
    languagePref: "விருப்பமான மொழி",
    aadhaar: "ஆதார் எண் (விருப்பத்தேர்வு)",
    organic: "இயற்கை தயாரிப்பு",
    category: "வகை",
    description: "விளக்கம்",
    season: "பருவம்",
    allItems: "அனைத்து பொருட்கள்",
    veggies: "காய்கறிகள்",
    fruits: "பழங்கள்",
    grains: "தானியங்கள்",
    adminVerify: "நிர்வாகி சரிபார்ப்பு",
    agentHub: "முகவர் மையம்",
    outForDelivery: "டெலிவரிக்கு தயாராக உள்ளது",
    getStarted: "இலவசமாக தொடங்குங்கள்",
    shopNow: "இப்போதே வாங்கவும்",
    isPrebooking: "முன்பதிவுக்கு கிடைக்கிறது",
    harvestDate: "எதிர்பார்க்கப்படும் அறுவடை தேதி",
    preBook: "முன்பதிவு",
    preBooked: "முன்பதிவு செய்யப்பட்டது",
    rewardPoints: "வெகுமதி புள்ளிகள்",
    experiencePoints: "அனுபவ புள்ளிகள்",
    usePoints: "தள்ளுபடிக்கு புள்ளிகளை பயன்படுத்தவும்",

    home: 'முகப்பு',
    seasonalSpecials: 'பருவகால சிறப்புகள்',
    freshlyHarvested: 'இந்த பருவத்தில் புதிதாக அறுவடை செய்யப்பட்டது!',
    list: 'பட்டியல்',
    map: 'வரைபடம்',
    placeOrder: 'ஆர்டர் செய்',
    deliveryOption: 'டெலிவரி விருப்பம்',
    buyAtFarm: 'பண்ணையில் வாங்குங்கள்',
    homeDelivery: 'ஹோம் டெலிவரி',
    paymentMethod: 'கட்டண முறை',
    cashOnDelivery: 'பணம் செலுத்தி பெறுதல்',
    payOnline: 'ஆன்லைனில் செலுத்துங்கள்',
    apply: 'பயன்படுத்து',
    billPreview: 'ரசீது முன்னோட்டம்',
    total: 'மொத்தம்',
    fetchWeather: 'வானிலை தகவலைப் பெறு',
    detecting: 'கண்டறியப்படுகிறது...',
    weatherData: 'வானிலை தரவு',
    demandForecaster: 'தேவை கணிப்பாளர்',
    predictDemand: 'தேவையை கணிக்கவும்',
    analyzing: 'பகுப்பாய்வு செய்யப்படுகிறது...',
    smartRoute: 'ஸ்மார்ட் வழியை மேம்படுத்து',
    optimizing: 'மேம்படுத்தப்படுகிறது...',
    routeGenerated: 'ஸ்மார்ட் வழி உருவாக்கப்பட்டது',
    totalDistance: 'மொத்த தூரம்',
    notifications: 'அறிவிப்புகள்',
    unread: 'படிக்காதவை',
    noNotifications: 'புதிய அறிவிப்புகள் இல்லை',
    myOrders: 'என் ஆர்டர்கள்',
    cancel: 'ரத்து செய்',
    confirm: 'உறுதிப்படுத்து',
    printBill: 'ரசீதை அச்சிடு',
  },
};

const LangContext = createContext();

export function LangProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem("lang") || "en");

  const changeLang = (l) => {
    setLang(l);
    localStorage.setItem("lang", l);
  };

  const t = (key) => translations[lang]?.[key] || translations["en"][key] || key;

  return (
    <LangContext.Provider value={{ lang, changeLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
